### ISSUE TITLE
Granularities to support

### ISSUE THREAD

**Issue by znicholls** [znicholls/CMIP6-json-data-citation-generator#1]
@MartinaSt I still don't understand exactly what you mean by granularities? Do you mean we should be able to handle filenames of the form

```
* <mip_era>.<activity_id>.<institution_id>.<source_id>
```

*and*

```
* <mip_era>.<activity_id>.<institution_id>.<source_id>.<experiment_id>
```

?

**Comment by MartinaSt** [comment]
@znicholls We provide two data references for the same files. 

The reason is that data users need to choose the data aggregation, which is keeping the number of data references in the reference list at a number acceptable for editors. One citation includes all data published by one institution with one model to one MIP and the second the same contribution to one experiment within the MIP.

My concern with your approach was: How does your tool know, if a JSON file for a model/MIP or an experiment data reference is to be created.

**Comment by znicholls** [comment]
Ah ok I see now!

Yes at the moment this tool only produces data references for experiment data. I could add a switch to produce reference files for both (or only one or the other depending on user preferences), would that be helpful?

To try and explain how things work at the moment in a bit more detail. The tool looks through a folder of files and makes a json for each unique source_id it finds (looking at the filenames). Hence it produces data references for experiments. I am guessing that we also want the ability to produce a json for each unique model-MIP-institution combination it finds? Hence this second file would apply to more files than the files I am currently producing (which apply to specific experiments)?

**Comment by znicholls** [comment]
To try and explain a bit better. Given the file list below

```
mole-fraction-of-c2f6-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp119-1-1-0_gn-15x360deg_201501-250012.nc
mole-fraction-of-c2f6-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp119-1-1-0_gr-0p5x360deg_201501-250012.nc
mole-fraction-of-c2f6-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp119-1-1-0_gr1-GMNHSH_2015-2500.nc
mole-fraction-of-c2f6-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp119-1-1-0_gr1-GMNHSH_201501-250012.nc
mole-fraction-of-c2f6-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp585-1-1-0_gr1-GMNHSH_2015-2500.nc
mole-fraction-of-hfc134aeq-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp245-1-1-0_gr-0p5x360deg_201501-250012.nc
mole-fraction-of-methyl-chloride-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp370-1-1-0_gr1-GMNHSH_2015-2500.nc
mole-fraction-of-methyl-chloride-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp370lowntcf-1-1-0_gr1-GMNHSH_2015-2500.nc
mole-fraction-of-methyl-chloride-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp534os-1-1-0_gr1-GMNHSH_2015-2500.nc
mole-fraction-of-so2f2-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp585-1-1-0_gn-15x360deg_201501-250012.nc
mole-fraction-of-so2f2-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp585-1-1-0_gr-0p5x360deg_201501-250012.nc
mole-fraction-of-so2f2-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp585-1-1-0_gr1-GMNHSH_2015-2500.nc
mole-fraction-of-so2f2-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoM-ssp585-1-1-0_gr1-GMNHSH_201501-250012.nc
mole-fraction-of-so2f2-in-air_input4MIPs_GHGConcentrations_ScenarioMIP_UoF-BIGMODEL-ssp585-1-1-0_gr1-GMNHSH_201501-250012.nc
```

We should create the following `json` files?

```
# experiment specific files
# ------------------------
UoM-ssp119-1-1-0.json
UoM-ssp585-1-1-0.json
UoM-ssp245-1-1-0.json
UoM-ssp370-1-1-0.json
UoM-ssp370lowntcf-1-1-0.json
UoM-ssp534os-1-1-0.json
UoF-BIGMODEL-ssp585-1-1-0.json

# MIP institution model specific files
# ----------------------------------
UoF-BIGMODEL-ScenarioMIP.json
UoM-ScenarioMIP.json # no model so that is missing

# or should they include a version number (to make something like)
# -----------------------------------------------------------------
UoM-ScenarioMIP-1-1-0.json
UoF-BIGMODEL-ScenarioMIP-1-1-0.json
```

**Comment by MartinaSt** [comment]
File list: You are aware that the files will lie in a directory tree? You walk through it when compiling the file list?

Experiment specific file naming: I suggest to add the source_id to the name. Institutions run multiple model configurations / source_ids or a citation manager providing data references for one model run with two different institution_ids. Best to include everything in the name: <institution_id>_<source_id>_<activity_id>[_experiment_id].json

Maybe it makes sense for you to have a look at the pre-published CMIP6 files at: https://esgf-fedtest.dkrz.de/search/testproject/?mip_era=CMIP6&activity_id=CMIP

**Comment by znicholls** [comment]
> File list: You are aware that the files will lie in a directory tree? You walk through it when compiling the file list?

Yes that would also be easy to do

> Experiment specific file naming: I suggest to add the source_id to the name. Institutions run multiple model configurations / source_ids or a citation manager providing data references for one model run with two different institution_ids. Best to include everything in the name: <institution_id><source_id><activity_id>[_experiment_id].json

Great sounds sensible and easy to do

> Maybe it makes sense for you to have a look at the pre-published CMIP6 files at: https://esgf-fedtest.dkrz.de/search/testproject/?mip_era=CMIP6&activity_id=CMIP

Have done. Just to make sure I understand, is there anything I should take away from looking at this except that we should create files of the form `<institution_id>_<source_id>_<activity_id>[_<experiment_id>].json` and that there are lots of files?

**Comment by MartinaSt** [comment]
> Have done. Just to make sure I understand, is there anything I should take away from looking at this except that we should create files of the form <institution_id>_<source_id>_<activity_id>[_<experiment_id>].json and that there are lots of files?

Yes, lots of files but few created JSONs.
