### ISSUE TITLE
Discussion: Add netCDF reading

### ISSUE THREAD

**Issue by znicholls** [znicholls/CMIP6-json-data-citation-generator#20]
This would make it possible to generate the citation purely from the file, irrespective of its name or directory (and we could also rename and put in the right path too..). However it makes installation harder as you need a netCDF reader installed in the right environment too. I think it's probably the right move, but one for discussion now.

**Comment by znicholls** [comment]
After conversations with @durack1, this side of things is handled by https://github.com/PCMDI/cmor and does not belong here hence close

**Comment by durack1** [comment]
@znicholls to be clear, in the use/demo provided at [PCMDI/input4MIPs-cmor-tables/demo/MRI-JMA-JRA55-do-1-3](https://github.com/PCMDI/input4MIPs-cmor-tables/tree/master/demo/MRI-JMA-JRA55-do-1-3) you could use both CDMS (the current demo uses this IO package) along with netcdf4python or another IO library to hand memory objects to CMOR for writing

**Comment by znicholls** [comment]
Yep nice. 

The only conclusion for this issue was to not include a netCDF writer/reader in this repo as it makes installation harder and the reading/writing steps should be done earlier in the pipeline.
