### ISSUE TITLE
Adding version to citation

### ISSUE THREAD

**Issue by znicholls** [znicholls/CMIP6-json-data-citation-generator#26]
# Bug Report

## Describe the bug

On the landing pages, e.g. https://cera-www.dkrz.de/WDCC/ui/cerasearch/cmip6?input=input4MIPs.CMIP6.ScenarioMIP.UoM.UoM-IMAGE-ssp126-1-2-1.atmos.mon.mole_fraction_of_halon1211_in_air.gr-0p5x360deg.20181127 the citation has ' Version YYYYMMDD'. 

@MartinaSt is this how it is meant to be?

**Comment by MartinaSt** [comment]
@znicholls : The version is explained in the footnote ;-)

As our citations (esp. for CMIP6) are assigned for a data collection of evolving data (including all versions), a data user citing the data needs to specify the ESGF dataset version to specify the data subset used. ESGF CoG support filtering for version ranges in the "More Search Options" section.

I have to admit that the version is a bit confusing for input4MIPs as there is also a version included in the source_id.

To be specific for your example:

- The data reference (DOI) is assigned for all datasets in "input4MIPs.CMIP6.ScenarioMIP.UoM.UoM-IMAGE-ssp126-1-2-1"
- landing page for DOI: https://cera-www.dkrz.de/WDCC/ui/cerasearch/cmip6?input=input4MIPs.CMIP6.ScenarioMIP.UoM.UoM-IMAGE-ssp126-1-2-1
- Recommended data reference: 
"Meinshausen, Malte; Nicholls, Zebedee R. J. (2018). UoM-IMAGE-ssp126-1-2-1 GHG concentrations. Version 20181127. Earth System Grid Federation. https://doi.org/10.22033/ESGF/input4MIPs.9865."

You find the ESGF version in the last part of your copied URL. I guess you were directed to the landing page from the ESGF CoG?

Btw, is the footnote understandable?

**Comment by znicholls** [comment]
Ok I see now. 

> Btw, is the footnote understandable?

It is understandable but it is, as you say, confusing. I think for two major reasons:

1. there is a version included in the source_id
1. the version you're meant to use (YYYYMMDD) isn't actually on the landing page and is only accessible on the 'Metadata export' pages or via the url

Is it not possible to fill in that data, given you already fill it in in the url?

**Comment by MartinaSt** [comment]
No, unfortunately, I have no information about the ESGF versions in the citation service.
